# Dockerfile
FROM jenkins/jenkins:lts
USER root
# Install Git
RUN apt-get update && \
apt-get install -y git && \
rm -rf /var/lib/apt/lists/*
# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
apt-get install -y nodejs && \
rm -rf /var/lib/apt/lists/*
USER jenkins